// <auto-generated />
using System;
using BomPraTi.Catalog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace BomPraTi.Catalog.Data.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260822174037_InitialCatalog")]
    partial class InitialCatalog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.PostgreSql)
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BomPraTi.Catalog.Domain.Brand", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().IsRequired().HasMaxLength(40).HasColumnType("character varying(40)").HasColumnName("ConcurrencyStamp");
                b.Property<string>("ExtraProperties").IsRequired().HasColumnType("text").HasColumnName("ExtraProperties");
                b.Property<string>("Name").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)");
                b.Property<string>("NormalizedName").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)");
                b.HasKey("Id");
                b.HasIndex("NormalizedName").IsUnique();
                b.ToTable("CatalogBrands", (string)null);
            });

            modelBuilder.Entity("BomPraTi.Catalog.Domain.Generation", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().IsRequired().HasMaxLength(40).HasColumnType("character varying(40)").HasColumnName("ConcurrencyStamp");
                b.Property<int?>("EndYear").HasColumnType("integer");
                b.Property<string>("ExtraProperties").IsRequired().HasColumnType("text").HasColumnName("ExtraProperties");
                b.Property<Guid>("ModelId").HasColumnType("uuid");
                b.Property<string>("Name").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)");
                b.Property<int?>("StartYear").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("ModelId", "Name");
                b.ToTable("CatalogGenerations", (string)null);
            });

            modelBuilder.Entity("BomPraTi.Catalog.Domain.Vehicle", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<Guid>("BrandId").HasColumnType("uuid");
                b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().IsRequired().HasMaxLength(40).HasColumnType("character varying(40)").HasColumnName("ConcurrencyStamp");
                b.Property<string>("ExtraProperties").IsRequired().HasColumnType("text").HasColumnName("ExtraProperties");
                b.Property<Guid?>("GenerationId").HasColumnType("uuid");
                b.Property<Guid>("ModelId").HasColumnType("uuid");
                b.Property<int?>("ModelYear").HasColumnType("integer");
                b.Property<Guid>("VersionId").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("BrandId", "ModelId", "GenerationId", "VersionId", "ModelYear").IsUnique();
                b.ToTable("CatalogVehicles", (string)null);
            });

            modelBuilder.Entity("BomPraTi.Catalog.Domain.VehicleModel", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<Guid>("BrandId").HasColumnType("uuid");
                b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().IsRequired().HasMaxLength(40).HasColumnType("character varying(40)").HasColumnName("ConcurrencyStamp");
                b.Property<string>("ExtraProperties").IsRequired().HasColumnType("text").HasColumnName("ExtraProperties");
                b.Property<string>("Name").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)");
                b.Property<string>("NormalizedName").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)");
                b.HasKey("Id");
                b.HasIndex("BrandId", "NormalizedName").IsUnique();
                b.ToTable("CatalogModels", (string)null);
            });

            modelBuilder.Entity("BomPraTi.Catalog.Domain.VehicleVersion", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().IsRequired().HasMaxLength(40).HasColumnType("character varying(40)").HasColumnName("ConcurrencyStamp");
                b.Property<string>("ExtraProperties").IsRequired().HasColumnType("text").HasColumnName("ExtraProperties");
                b.Property<Guid?>("GenerationId").HasColumnType("uuid");
                b.Property<Guid>("ModelId").HasColumnType("uuid");
                b.Property<string>("Name").IsRequired().HasMaxLength(180).HasColumnType("character varying(180)");
                b.Property<string>("NormalizedName").IsRequired().HasMaxLength(180).HasColumnType("character varying(180)");
                b.HasKey("Id");
                b.HasIndex("ModelId", "GenerationId", "NormalizedName").IsUnique();
                b.ToTable("CatalogVersions", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}
