<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.Autofac" Version="10.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../modules/catalog/src/BomPraTi.Catalog/BomPraTi.Catalog.csproj" />
    <ProjectReference Include="../../modules/sellers/src/BomPraTi.Sellers/BomPraTi.Sellers.csproj" />
  </ItemGroup>

</Project>
