<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>BomPraTi.Media</RootNamespace>
    <AssemblyName>BomPraTi.Media</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application" />
    <PackageReference Include="Volo.Abp.Ddd.Domain" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.PostgreSql" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../BomPraTi.Media.Contracts/BomPraTi.Media.Contracts.csproj" />
  </ItemGroup>
</Project>
