#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import json
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs/generated/repository-facts.md"
ABP_FRAMEWORK_EXACT = {
    "Volo.Abp.Core",
    "Volo.Abp.AspNetCore.Mvc",
}
ABP_FRAMEWORK_PREFIXES = (
    "Volo.Abp.Ddd.",
    "Volo.Abp.EntityFrameworkCore",
)


def is_abp_framework_package(name: str) -> bool:
    return name in ABP_FRAMEWORK_EXACT or any(name.startswith(prefix) for prefix in ABP_FRAMEWORK_PREFIXES)


def xml_values(path: Path) -> tuple[set[str], set[str]]:
    frameworks: set[str] = set()
    abp_versions: set[str] = set()
    try:
        root = ET.parse(path).getroot()
    except ET.ParseError as exc:
        raise SystemExit(f"Invalid project XML: {path.relative_to(ROOT)}: {exc}") from exc

    for element in root.iter():
        tag = element.tag.rsplit("}", 1)[-1]
        if tag in {"TargetFramework", "TargetFrameworks"} and element.text:
            frameworks.update(value.strip() for value in element.text.split(";") if value.strip())
        if tag in {"PackageReference", "PackageVersion"}:
            include = element.attrib.get("Include", "")
            version = element.attrib.get("Version")
            if version and is_abp_framework_package(include):
                abp_versions.add(version)
    return frameworks, abp_versions


def render() -> str:
    sdk_version = json.loads((ROOT / "global.json").read_text(encoding="utf-8"))["sdk"]["version"]
    projects = [p for p in sorted(ROOT.rglob("*.csproj")) if not {"bin", "obj"} & set(p.parts)]
    test_projects = [p for p in projects if p.is_relative_to(ROOT / "tests")]

    frameworks: set[str] = set()
    abp_versions: set[str] = set()
    for path in projects + sorted(ROOT.rglob("Directory.Packages.props")):
        path_frameworks, path_abp_versions = xml_values(path)
        frameworks.update(path_frameworks)
        abp_versions.update(path_abp_versions)

    modules = sorted(
        path.name for path in (ROOT / "modules").iterdir()
        if path.is_dir() and (path / "src").is_dir()
    )
    workflows = sorted(path.name for path in (ROOT / ".github/workflows").glob("*.yml"))
    active_plans = sorted(
        path.name for path in (ROOT / "docs/exec-plans/active").glob("*.md")
        if path.name.lower() != "readme.md"
    )

    def bullet(values) -> str:
        ordered = sorted(values)
        return ", ".join(f"`{value}`" for value in ordered) if ordered else "none"

    return "\n".join([
        "# Generated repository facts",
        "",
        "> Generated by `scripts/generate-repo-facts.py`. Do not edit manually.",
        "",
        f"- .NET SDK baseline: `{sdk_version}`",
        f"- Target frameworks found in project files: {bullet(frameworks)}",
        f"- ABP framework versions detected: {bullet(abp_versions)}",
        f"- Project files (`*.csproj`): **{len(projects)}**",
        f"- Test project files under `tests/`: **{len(test_projects)}**",
        f"- Business module directories: **{len(modules)}** — {bullet(modules)}",
        f"- GitHub workflow files: **{len(workflows)}** — {bullet(workflows)}",
        f"- Active execution plans: **{len(active_plans)}** — {bullet(active_plans)}",
        "",
        "Runtime readiness is intentionally not copied here. Use the checks on the current commit/PR as defined by `docs/QUALITY.md`.",
        "",
    ])


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()

    if args.write:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(content, encoding="utf-8")
        print(f"wrote {OUTPUT.relative_to(ROOT)}")
        return 0
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != content:
            print("generated repository facts are stale; run:\n  python3 scripts/generate-repo-facts.py --write")
            print("\n".join(difflib.unified_diff(
                current.splitlines(), content.splitlines(),
                fromfile=str(OUTPUT.relative_to(ROOT)), tofile="generated", lineterm="",
            )))
            return 1
        print("GENERATED REPOSITORY FACTS: PASSED")
        return 0

    print(content, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
