#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import json
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs/generated/repository-facts.md"


def values_from_csproj(path: Path) -> tuple[set[str], set[str]]:
    frameworks: set[str] = set()
    abp_versions: set[str] = set()
    try:
        root = ET.parse(path).getroot()
    except ET.ParseError as exc:
        raise SystemExit(f"Invalid csproj XML: {path.relative_to(ROOT)}: {exc}") from exc

    for element in root.iter():
        tag = element.tag.rsplit("}", 1)[-1]
        if tag in {"TargetFramework", "TargetFrameworks"} and element.text:
            frameworks.update(value.strip() for value in element.text.split(";") if value.strip())
        if tag == "PackageReference":
            include = element.attrib.get("Include", "")
            version = element.attrib.get("Version")
            if include.startswith("Volo.Abp.") and version:
                abp_versions.add(version)
    return frameworks, abp_versions


def render() -> str:
    global_json = json.loads((ROOT / "global.json").read_text(encoding="utf-8"))
    sdk_version = global_json["sdk"]["version"]

    projects = sorted(ROOT.rglob("*.csproj"))
    projects = [p for p in projects if not {"bin", "obj"} & set(p.parts)]
    test_projects = [p for p in projects if p.is_relative_to(ROOT / "tests")]

    frameworks: set[str] = set()
    abp_versions: set[str] = set()
    for project in projects:
        project_frameworks, project_abp_versions = values_from_csproj(project)
        frameworks.update(project_frameworks)
        abp_versions.update(project_abp_versions)

    modules_root = ROOT / "modules"
    modules = sorted(
        path.name
        for path in modules_root.iterdir()
        if path.is_dir() and (path / "src").is_dir()
    )
    workflows = sorted(path.name for path in (ROOT / ".github/workflows").glob("*.yml"))
    active_plans = sorted(
        path.name
        for path in (ROOT / "docs/exec-plans/active").glob("*.md")
        if path.name.lower() != "readme.md"
    )

    def bullet(values: list[str] | set[str]) -> str:
        values = sorted(values)
        return ", ".join(f"`{value}`" for value in values) if values else "none"

    lines = [
        "# Generated repository facts",
        "",
        "> Generated by `scripts/generate-repo-facts.py`. Do not edit manually.",
        "",
        f"- .NET SDK baseline: `{sdk_version}`",
        f"- Target frameworks found in project files: {bullet(frameworks)}",
        f"- ABP package versions explicitly referenced: {bullet(abp_versions)}",
        f"- Project files (`*.csproj`): **{len(projects)}**",
        f"- Test project files under `tests/`: **{len(test_projects)}**",
        f"- Business module directories: **{len(modules)}** — {bullet(modules)}",
        f"- GitHub workflow files: **{len(workflows)}** — {bullet(workflows)}",
        f"- Active execution plans: **{len(active_plans)}** — {bullet(active_plans)}",
        "",
        "Runtime readiness is intentionally not copied here. Use the checks on the current commit/PR as defined by `docs/QUALITY.md`.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="write the generated document")
    mode.add_argument("--check", action="store_true", help="fail if the generated document is stale")
    args = parser.parse_args()

    content = render()
    if args.write:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(content, encoding="utf-8")
        print(f"wrote {OUTPUT.relative_to(ROOT)}")
        return 0

    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != content:
            print("generated repository facts are stale; run:")
            print("  python3 scripts/generate-repo-facts.py --write")
            print("\n".join(difflib.unified_diff(
                current.splitlines(),
                content.splitlines(),
                fromfile=str(OUTPUT.relative_to(ROOT)),
                tofile="generated",
                lineterm="",
            )))
            return 1
        print("GENERATED REPOSITORY FACTS: PASSED")
        return 0

    print(content, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
